/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as LecturerRouteImport } from './routes/lecturer'
import { Route as StudentRouteImport } from './routes/student'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminMaterialsRouteImport } from './routes/admin.materials'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminProfileRouteImport } from './routes/admin.profile'
import { Route as AdminRegisterRouteImport } from './routes/admin.register'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminLoginRouteImport } from './routes/admin_.login'
import { Route as LecturerIndexRouteImport } from './routes/lecturer.index'
import { Route as LecturerMaterialsRouteImport } from './routes/lecturer.materials'
import { Route as LecturerNotificationsRouteImport } from './routes/lecturer.notifications'
import { Route as LecturerProfileRouteImport } from './routes/lecturer.profile'
import { Route as LecturerUploadRouteImport } from './routes/lecturer.upload'
import { Route as LecturerLoginRouteImport } from './routes/lecturer_.login'
import { Route as StudentIndexRouteImport } from './routes/student.index'
import { Route as StudentMaterialsRouteImport } from './routes/student.materials'
import { Route as StudentNotificationsRouteImport } from './routes/student.notifications'
import { Route as StudentProfileRouteImport } from './routes/student.profile'
import { Route as StudentLoginRouteImport } from './routes/student_.login'
import { Route as AdminUsersIndexRouteImport } from './routes/admin.users.index'
import { Route as AdminUsersUserIdRouteImport } from './routes/admin.users.$userId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LecturerRoute = LecturerRouteImport.update({
  id: '/lecturer',
  path: '/lecturer',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMaterialsRoute = AdminMaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRegisterRoute = AdminRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin_/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LecturerIndexRoute = LecturerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LecturerRoute,
} as any)
const LecturerMaterialsRoute = LecturerMaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => LecturerRoute,
} as any)
const LecturerNotificationsRoute = LecturerNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => LecturerRoute,
} as any)
const LecturerProfileRoute = LecturerProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => LecturerRoute,
} as any)
const LecturerUploadRoute = LecturerUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => LecturerRoute,
} as any)
const LecturerLoginRoute = LecturerLoginRouteImport.update({
  id: '/lecturer_/login',
  path: '/lecturer/login',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentRoute,
} as any)
const StudentMaterialsRoute = StudentMaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => StudentRoute,
} as any)
const StudentNotificationsRoute = StudentNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => StudentRoute,
} as any)
const StudentProfileRoute = StudentProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => StudentRoute,
} as any)
const StudentLoginRoute = StudentLoginRouteImport.update({
  id: '/student_/login',
  path: '/student/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminUsersRoute,
} as any)
const AdminUsersUserIdRoute = AdminUsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => AdminUsersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/lecturer': typeof LecturerRouteWithChildren
  '/student': typeof StudentRouteWithChildren
  '/admin/materials': typeof AdminMaterialsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/register': typeof AdminRegisterRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/lecturer/materials': typeof LecturerMaterialsRoute
  '/lecturer/notifications': typeof LecturerNotificationsRoute
  '/lecturer/profile': typeof LecturerProfileRoute
  '/lecturer/upload': typeof LecturerUploadRoute
  '/lecturer/login': typeof LecturerLoginRoute
  '/student/materials': typeof StudentMaterialsRoute
  '/student/notifications': typeof StudentNotificationsRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/login': typeof StudentLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/lecturer/': typeof LecturerIndexRoute
  '/student/': typeof StudentIndexRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/admin/users/': typeof AdminUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/materials': typeof AdminMaterialsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/register': typeof AdminRegisterRoute
  '/admin/login': typeof AdminLoginRoute
  '/lecturer/materials': typeof LecturerMaterialsRoute
  '/lecturer/notifications': typeof LecturerNotificationsRoute
  '/lecturer/profile': typeof LecturerProfileRoute
  '/lecturer/upload': typeof LecturerUploadRoute
  '/lecturer/login': typeof LecturerLoginRoute
  '/student/materials': typeof StudentMaterialsRoute
  '/student/notifications': typeof StudentNotificationsRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/login': typeof StudentLoginRoute
  '/admin': typeof AdminIndexRoute
  '/lecturer': typeof LecturerIndexRoute
  '/student': typeof StudentIndexRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/admin/users': typeof AdminUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/lecturer': typeof LecturerRouteWithChildren
  '/student': typeof StudentRouteWithChildren
  '/admin/materials': typeof AdminMaterialsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/register': typeof AdminRegisterRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/admin_/login': typeof AdminLoginRoute
  '/lecturer/materials': typeof LecturerMaterialsRoute
  '/lecturer/notifications': typeof LecturerNotificationsRoute
  '/lecturer/profile': typeof LecturerProfileRoute
  '/lecturer/upload': typeof LecturerUploadRoute
  '/lecturer_/login': typeof LecturerLoginRoute
  '/student/materials': typeof StudentMaterialsRoute
  '/student/notifications': typeof StudentNotificationsRoute
  '/student/profile': typeof StudentProfileRoute
  '/student_/login': typeof StudentLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/lecturer/': typeof LecturerIndexRoute
  '/student/': typeof StudentIndexRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/admin/users/': typeof AdminUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/lecturer'
    | '/student'
    | '/admin/materials'
    | '/admin/notifications'
    | '/admin/profile'
    | '/admin/register'
    | '/admin/users'
    | '/admin/login'
    | '/lecturer/materials'
    | '/lecturer/notifications'
    | '/lecturer/profile'
    | '/lecturer/upload'
    | '/lecturer/login'
    | '/student/materials'
    | '/student/notifications'
    | '/student/profile'
    | '/student/login'
    | '/admin/'
    | '/lecturer/'
    | '/student/'
    | '/admin/users/$userId'
    | '/admin/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/materials'
    | '/admin/notifications'
    | '/admin/profile'
    | '/admin/register'
    | '/admin/login'
    | '/lecturer/materials'
    | '/lecturer/notifications'
    | '/lecturer/profile'
    | '/lecturer/upload'
    | '/lecturer/login'
    | '/student/materials'
    | '/student/notifications'
    | '/student/profile'
    | '/student/login'
    | '/admin'
    | '/lecturer'
    | '/student'
    | '/admin/users/$userId'
    | '/admin/users'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/lecturer'
    | '/student'
    | '/admin/materials'
    | '/admin/notifications'
    | '/admin/profile'
    | '/admin/register'
    | '/admin/users'
    | '/admin_/login'
    | '/lecturer/materials'
    | '/lecturer/notifications'
    | '/lecturer/profile'
    | '/lecturer/upload'
    | '/lecturer_/login'
    | '/student/materials'
    | '/student/notifications'
    | '/student/profile'
    | '/student_/login'
    | '/admin/'
    | '/lecturer/'
    | '/student/'
    | '/admin/users/$userId'
    | '/admin/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LecturerRoute: typeof LecturerRouteWithChildren
  StudentRoute: typeof StudentRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  LecturerLoginRoute: typeof LecturerLoginRoute
  StudentLoginRoute: typeof StudentLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lecturer': {
      id: '/lecturer'
      path: '/lecturer'
      fullPath: '/lecturer'
      preLoaderRoute: typeof LecturerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/materials': {
      id: '/admin/materials'
      path: '/materials'
      fullPath: '/admin/materials'
      preLoaderRoute: typeof AdminMaterialsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/register': {
      id: '/admin/register'
      path: '/register'
      fullPath: '/admin/register'
      preLoaderRoute: typeof AdminRegisterRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin_/login': {
      id: '/admin_/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lecturer/': {
      id: '/lecturer/'
      path: '/'
      fullPath: '/lecturer/'
      preLoaderRoute: typeof LecturerIndexRouteImport
      parentRoute: typeof LecturerRoute
    }
    '/lecturer/materials': {
      id: '/lecturer/materials'
      path: '/materials'
      fullPath: '/lecturer/materials'
      preLoaderRoute: typeof LecturerMaterialsRouteImport
      parentRoute: typeof LecturerRoute
    }
    '/lecturer/notifications': {
      id: '/lecturer/notifications'
      path: '/notifications'
      fullPath: '/lecturer/notifications'
      preLoaderRoute: typeof LecturerNotificationsRouteImport
      parentRoute: typeof LecturerRoute
    }
    '/lecturer/profile': {
      id: '/lecturer/profile'
      path: '/profile'
      fullPath: '/lecturer/profile'
      preLoaderRoute: typeof LecturerProfileRouteImport
      parentRoute: typeof LecturerRoute
    }
    '/lecturer/upload': {
      id: '/lecturer/upload'
      path: '/upload'
      fullPath: '/lecturer/upload'
      preLoaderRoute: typeof LecturerUploadRouteImport
      parentRoute: typeof LecturerRoute
    }
    '/lecturer_/login': {
      id: '/lecturer_/login'
      path: '/lecturer/login'
      fullPath: '/lecturer/login'
      preLoaderRoute: typeof LecturerLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/materials': {
      id: '/student/materials'
      path: '/materials'
      fullPath: '/student/materials'
      preLoaderRoute: typeof StudentMaterialsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/notifications': {
      id: '/student/notifications'
      path: '/notifications'
      fullPath: '/student/notifications'
      preLoaderRoute: typeof StudentNotificationsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/profile': {
      id: '/student/profile'
      path: '/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof StudentProfileRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student_/login': {
      id: '/student_/login'
      path: '/student/login'
      fullPath: '/student/login'
      preLoaderRoute: typeof StudentLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminUsersRoute
    }
    '/admin/users/$userId': {
      id: '/admin/users/$userId'
      path: '/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AdminUsersUserIdRouteImport
      parentRoute: typeof AdminUsersRoute
    }
  }
}

interface AdminUsersRouteChildren {
  AdminUsersUserIdRoute: typeof AdminUsersUserIdRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
}

const AdminUsersRouteChildren: AdminUsersRouteChildren = {
  AdminUsersUserIdRoute: AdminUsersUserIdRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
}

const AdminUsersRouteWithChildren = AdminUsersRoute._addFileChildren(
  AdminUsersRouteChildren,
)

interface AdminRouteChildren {
  AdminMaterialsRoute: typeof AdminMaterialsRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminRegisterRoute: typeof AdminRegisterRoute
  AdminUsersRoute: typeof AdminUsersRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminMaterialsRoute: AdminMaterialsRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminRegisterRoute: AdminRegisterRoute,
  AdminUsersRoute: AdminUsersRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface LecturerRouteChildren {
  LecturerMaterialsRoute: typeof LecturerMaterialsRoute
  LecturerNotificationsRoute: typeof LecturerNotificationsRoute
  LecturerProfileRoute: typeof LecturerProfileRoute
  LecturerUploadRoute: typeof LecturerUploadRoute
  LecturerIndexRoute: typeof LecturerIndexRoute
}

const LecturerRouteChildren: LecturerRouteChildren = {
  LecturerMaterialsRoute: LecturerMaterialsRoute,
  LecturerNotificationsRoute: LecturerNotificationsRoute,
  LecturerProfileRoute: LecturerProfileRoute,
  LecturerUploadRoute: LecturerUploadRoute,
  LecturerIndexRoute: LecturerIndexRoute,
}

const LecturerRouteWithChildren = LecturerRoute._addFileChildren(
  LecturerRouteChildren,
)

interface StudentRouteChildren {
  StudentMaterialsRoute: typeof StudentMaterialsRoute
  StudentNotificationsRoute: typeof StudentNotificationsRoute
  StudentProfileRoute: typeof StudentProfileRoute
  StudentIndexRoute: typeof StudentIndexRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentMaterialsRoute: StudentMaterialsRoute,
  StudentNotificationsRoute: StudentNotificationsRoute,
  StudentProfileRoute: StudentProfileRoute,
  StudentIndexRoute: StudentIndexRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LecturerRoute: LecturerRouteWithChildren,
  StudentRoute: StudentRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  LecturerLoginRoute: LecturerLoginRoute,
  StudentLoginRoute: StudentLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
