# Generated by Django 6.0.8 on 2026-08-06 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_courseenrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='file_hash',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
    ]
