# Generated by Django 6.0.8 on 2026-08-06 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_material_file_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='staff_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
